# Generated by Django 4.2.10 on 2024-02-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='img_source',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
